version: '3.8'

services:
  web:
    build: .
    ports:
      - "3016:3016"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Vignesh@9#
      - MYSQL_DATABASE=urbanclean_db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Vignesh@9#
      - MYSQL_DATABASE=urbanclean_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 